const champions = [
    { name: "Aatrox", id: "aatrox" },
    { name: "Ahri", id: "ahri" },
    { name: "Akali", id: "akali" },
    { name: "Akshan", id: "akshan" },
    { name: "Alistar", id: "alistar" },
    { name: "Amumu", id: "amumu" },
    { name: "Anivia", id: "anivia" },
    { name: "Annie", id: "annie" },
    { name: "Aphelios", id: "aphelios" },
    { name: "Ashe", id: "ashe" },
    { name: "Aurelion Sol", id: "aurelionsol" },
    { name: "Azir", id: "azir" },
    { name: "Bard", id: "bard" },
    { name: "Bel'Veth", id: "belveth" },
    { name: "Blitzcrank", id: "blitzcrank" },
    { name: "Brand", id: "brand" },
    { name: "Braum", id: "braum" },
    { name: "Caitlyn", id: "caitlyn" },
    { name: "Camille", id: "camille" },
    { name: "Cassiopeia", id: "cassiopeia" },
    { name: "Cho'Gath", id: "chogath" },
    { name: "Corki", id: "corki" },
    { name: "Darius", id: "darius" },
    { name: "Diana", id: "diana" },
    { name: "Dr. Mundo", id: "drmundo" },
    { name: "Draven", id: "draven" },
    { name: "Ekko", id: "ekko" },
    { name: "Elise", id: "elise" },
    { name: "Evelynn", id: "evelynn" },
    { name: "Ezreal", id: "ezreal" },
    { name: "Fiddlesticks", id: "fiddlesticks" },
    { name: "Fiora", id: "fiora" },
    { name: "Fizz", id: "fizz" },
    { name: "Galio", id: "galio" },
    { name: "Gangplank", id: "gangplank" },
    { name: "Garen", id: "garen" },
    { name: "Gnar", id: "gnar" },
    { name: "Gragas", id: "gragas" },
    { name: "Graves", id: "graves" },
    { name: "Gwen", id: "gwen" },
    { name: "Hecarim", id: "hecarim" },
    { name: "Heimerdinger", id: "heimerdinger" },
    { name: "Illaoi", id: "illaoi" },
    { name: "Irelia", id: "irelia" },
    { name: "Ivern", id: "ivern" },
    { name: "Janna", id: "janna" },
    { name: "Jarvan IV", id: "jarvaniv" },
    { name: "Jax", id: "jax" },
    { name: "Jayce", id: "jayce" },
    { name: "Jhin", id: "jhin" },
    { name: "Jinx", id: "jinx" },
    { name: "K'Sante", id: "ksante" },
    { name: "Kai'Sa", id: "kaisa" },
    { name: "Kalista", id: "kalista" },
    { name: "Karma", id: "karma" },
    { name: "Karthus", id: "karthus" },
    { name: "Kassadin", id: "kassadin" },
    { name: "Katarina", id: "katarina" },
    { name: "Kayle", id: "kayle" },
    { name: "Kayn", id: "kayn" },
    { name: "Kennen", id: "kennen" },
    { name: "Kha'Zix", id: "khazix" },
    { name: "Kindred", id: "kindred" },
    { name: "Kled", id: "kled" },
    { name: "Kog'Maw", id: "kogmaw" },
    { name: "LeBlanc", id: "leblanc" },
    { name: "Lee Sin", id: "leesin" },
    { name: "Leona", id: "leona" },
    { name: "Lillia", id: "lillia" },
    { name: "Lissandra", id: "lissandra" },
    { name: "Lucian", id: "lucian" },
    { name: "Lulu", id: "lulu" },
    { name: "Lux", id: "lux" },
    { name: "Malphite", id: "malphite" },
    { name: "Malzahar", id: "malzahar" },
    { name: "Maokai", id: "maokai" },
    { name: "Master Yi", id: "masteryi" },
    { name: "Milio", id: "milio" },
    { name: "Miss Fortune", id: "missfortune" },
    { name: "Mordekaiser", id: "mordekaiser" },
    { name: "Morgana", id: "morgana" },
    { name: "Nami", id: "nami" },
    { name: "Nasus", id: "nasus" },
    { name: "Nautilus", id: "nautilus" },
    { name: "Neeko", id: "neeko" },
    { name: "Nidalee", id: "nidalee" },
    { name: "Nilah", id: "nilah" },
    { name: "Nocturne", id: "nocturne" },
    { name: "Nunu & Willump", id: "nunu" },
    { name: "Olaf", id: "olaf" },
    { name: "Orianna", id: "orianna" },
    { name: "Ornn", id: "ornn" },
    { name: "Pantheon", id: "pantheon" },
    { name: "Poppy", id: "poppy" },
    { name: "Pyke", id: "pyke" },
    { name: "Qiyana", id: "qiyana" },
    { name: "Quinn", id: "quinn" },
    { name: "Rakan", id: "rakan" },
    { name: "Rammus", id: "rammus" },
    { name: "Rek'Sai", id: "reksai" },
    { name: "Rell", id: "rell" },
    { name: "Renata Glasc", id: "renata" },
    { name: "Renekton", id: "renekton" },
    { name: "Rengar", id: "rengar" },
    { name: "Riven", id: "riven" },
    { name: "Rumble", id: "rumble" },
    { name: "Ryze", id: "ryze" },
    { name: "Samira", id: "samira" },
    { name: "Sejuani", id: "sejuani" },
    { name: "Senna", id: "senna" },
    { name: "Seraphine", id: "seraphine" },
    { name: "Sett", id: "sett" },
    { name: "Shaco", id: "shaco" },
    { name: "Shen", id: "shen" },
    { name: "Shyvana", id: "shyvana" },
    { name: "Singed", id: "singed" },
    { name: "Sion", id: "sion" },
    { name: "Sivir", id: "sivir" },
    { name: "Skarner", id: "skarner" },
    { name: "Sona", id: "sona" },
    { name: "Soraka", id: "soraka" },
    { name: "Swain", id: "swain" },
    { name: "Sylas", id: "sylas" },
    { name: "Syndra", id: "syndra" },
    { name: "Tahm Kench", id: "tahmkench" },
    { name: "Taliyah", id: "taliyah" },
    { name: "Talon", id: "talon" },
    { name: "Taric", id: "taric" },
    { name: "Teemo", id: "teemo" },
    { name: "Thresh", id: "thresh" },
    { name: "Tristana", id: "tristana" },
    { name: "Trundle", id: "trundle" },
    { name: "Tryndamere", id: "tryndamere" },
    { name: "Twisted Fate", id: "twistedfate" },
    { name: "Twitch", id: "twitch" },
    { name: "Udyr", id: "udyr" },
    { name: "Urgot", id: "urgot" },
    { name: "Varus", id: "varus" },
    { name: "Vayne", id: "vayne" },
    { name: "Veigar", id: "veigar" },
    { name: "Vel'Koz", id: "velkoz" },
    { name: "Vex", id: "vex" },
    { name: "Vi", id: "vi" },
    { name: "Viego", id: "viego" },
    { name: "Viktor", id: "viktor" },
    { name: "Vladimir", id: "vladimir" },
    { name: "Volibear", id: "volibear" },
    { name: "Warwick", id: "warwick" },
    { name: "Wukong", id: "wukong" },
    { name: "Xayah", id: "xayah" },
    { name: "Xerath", id: "xerath" },
    { name: "Xin Zhao", id: "xinzhao" },
    { name: "Yasuo", id: "yasuo" },
    { name: "Yone", id: "yone" },
    { name: "Yorick", id: "yorick" },
    { name: "Yuumi", id: "yuumi" },
    { name: "Zac", id: "zac" },
    { name: "Zed", id: "zed" },
    { name: "Zeri", id: "zeri" },
    { name: "Ziggs", id: "ziggs" },
    { name: "Zilean", id: "zilean" },
    { name: "Zoe", id: "zoe" },
    { name: "Zyra", id: "zyra" }
];

function getChampionImageUrl(championId) {
    return `https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/${championId.charAt(0).toUpperCase() + championId.slice(1)}.png`;
}